[theme]
primaryColor = "#1D4ED8"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
