[theme]
primaryColor = "#002045"
backgroundColor = "#f1f3f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#0d1c2e"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
